name: Publish

on:
  release:
    types: [published]

permissions: {}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
    with:
      build-musllinux: true

  publish-pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4.2.0
      with:
        pattern: artifact-*
        merge-multiple: true
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.14.0
